version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ./elasticsearch/kibana/:/usr/share/elasticsearch/kibana/
    ports:
    - "9300:9300"
    - "9200:9200"
    networks:
      unfetter-network:
        ipv4_address: 10.0.2.3     

  logstash:
    build: ./logstash
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
    ports:
      - "5000:5000"
      - "3515:3515"
      - "3516:3516"
      - "3517:3517"
    volumes:
    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./logstash/pipeline:/usr/share/logstash/pipeline
    links:
     - elasticsearch:elasticsearch
    networks:
      unfetter-network:
        ipv4_address: 10.0.2.2     

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    links:
    - elasticsearch:elasticsearch
    networks:
      unfetter-network:
        ipv4_address: 10.0.2.4
 
  analytic-system:
    build: ./analytic-system
    container_name: analytic-system
    links:
     - elasticsearch:elasticsearch
    volumes:
     - "./analytic-system/src:/usr/share/unfetter/src"
    networks:
      unfetter-network:
        ipv4_address: 10.0.2.5

   
  
networks:
  unfetter-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
        gateway: 10.0.2.1